
LATITUDE = "…"
LONGITUDE = "…"

GOOGLE_API_KEY = "…"
TRAFFIC_FROM = "…+FM"
#["TRAFFIC_FROM = f"${LATITUDE}-${LONGITUDE}"
TRAFFIC_1_THROUGH = "…+4FP"
TRAFFIC_2_THROUGH = "…+V9J"
TRAFFIC_TO = "…+GX"

AIRLY_API_KEY = "…"

OPENWEATHERMAP_API_KEY = "…"

